name: flutter_admin
description: 一个基于flutter的后台管理系统 - A management system based on flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cry: 0.2.4
  cupertino_icons: ^0.1.2
  charts_flutter: ^0.9.0
  flutter_custom_clippers: ^1.1.0
  font_awesome_flutter: ^8.5.0
  bot_toast: ^3.0.5
  flutter_colorpicker: any
  url_launcher: ^5.4.1
  universal_html: ^1.2.2
  mime_type: ^0.3.1
  image_picker: ^0.6.7
  image_picker_for_web: ^0.1.0
  video_player: ^0.10.5
  quiver: ^2.1.3
  global_configuration: ^1.6.0
  file_picker: ^2.1.4
  animations: ^1.1.2
  flutter_simple_treeview: ^2.0.2
  get: ^3.24.0
  get_storage: ^1.4.0
  syncfusion_flutter_charts: ^18.4.43+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0

dependency_overrides:
  intl: 0.17.0-nullsafety.2

flutter:
  uses-material-design: true
  assets:
    - config/

flutter_intl:
  enabled: true
